### PR TITLE
fixing issue 227

### LINKED ISSUE #227: FE covariate cohort feature input and output names changed
The settings for the FE cohorts as features used to be cohortDatabaseSchema/cohortTable and now they are covariateCohortDatabaseSchema/covariateCohortTable.  The code we added in PLP and PLPvalidation to overwrite these values when running the modules no longer work.

### PR DESCRIPTION
**Pull request by jreps**
Fixes issue 227

### CODE REVIEW

File: R/Module-PatientLevelPrediction.R [hunk 1]
```diff
@@ -171,9 +171,15 @@ PatientLevelPredictionModule <- R6::R6Class(
         }
 
         for (j in 1:length(covariateSettings)) {
+          if ("covariateCohortDatabaseSchema" %in% names(covariateSettings[[j]])) {
```
Comment (anthonysena) [inline R/Module-PatientLevelPrediction.R:174]: I thought the changes made in https://github.com/OHDSI/Strategus/pull/182/files would have handled this for you? Maybe that work needs further testing as my hope was that the function [.replaceCovariateSettings](https://github.com/OHDSI/Strategus/blob/v1.3.0/R/StrategusModule.R#L376) would have recursively traversed all settings to make these replacements?

**Review by anthonysena — CHANGES_REQUESTED** [review]

File: R/Module-PatientLevelPrediction.R (hunk 1 above)
Comment (jreps) [reply R/Module-PatientLevelPrediction.R:174]: For some reason that was not working when I ran code that needed the covariateCohortDatabaseSchema - was that code in the latest Strategus?

Comment (jreps) [reply R/Module-PatientLevelPrediction.R:174]: I'm not sure what version of Strategus I was using that failed.  But I just installed the latest main and it seems to be working, so I may have had an older version.  Perhaps we should add the old cohortTable and cohortDatabaseSchema edits for covariateSettings into the new function and remove the code from the prediction/validation modules as having it spread out is a little confusing?

Comment (anthonysena) [reply R/Module-PatientLevelPrediction.R:174]: So the changes referenced above were part of the Strategus v1.1 release. I'd support moving the old cohortTable and cohortDatabaseSchema edits into the `.replaceCovariateSettings` to make it work consistently across modules. I'd also support removing the code from the prediction/validation modules so we only have 1 place where that is done in the codebase. Thanks!
